<?php
$query = " 
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block` (
  `id_loffc_block` int(11) NOT NULL AUTO_INCREMENT,
  `width` float(10,2) NOT NULL,
  `show_title` tinyint(1) NOT NULL,
  `id_position` tinyint(2) NOT NULL,
  PRIMARY KEY (`id_loffc_block`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=57 ;

INSERT INTO `_DB_PREFIX_loffc_block` (`id_loffc_block`, `width`, `show_title`, `id_position`) VALUES
(1, 24.00, 0, 1),
(46, 24.00, 0, 2),
(54, 16.00, 1, 2),
(55, 16.00, 1, 2),
(56, 16.00, 1, 2),
(57, 28.00, 0, 2),
(58, 100.00, 0, 3);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item` (
  `id_loffc_block_item` int(11) NOT NULL AUTO_INCREMENT,
  `id_loffc_block` int(11) NOT NULL,
  `type` varchar(25) NOT NULL,
  `link` varchar(2000) NOT NULL,
  `linktype` varchar(25) NOT NULL,
  `link_content` varchar(2000) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `hook_name` varchar(100) NOT NULL,
  `latitude` varchar(25) NOT NULL,
  `longitude` varchar(25) NOT NULL,
  `addthis` tinyint(1) NOT NULL,
  `show_title` tinyint(1) NOT NULL DEFAULT '1',
  `target` varchar(20) NOT NULL DEFAULT '_self',
  `position` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=85 ;

INSERT INTO `_DB_PREFIX_loffc_block_item` (`id_loffc_block_item`, `id_loffc_block`, `type`, `link`, `linktype`, `link_content`, `module_name`, `hook_name`, `latitude`, `longitude`, `addthis`, `show_title`, `target`, `position`) VALUES
(72, 54, 'link', '', 'cms', '1', '', '', '', '', 0, 1, '_blank', 0),
(73, 54, 'link', '', 'cms', '4', '', '', '', '', 0, 1, '_self', 1),
(74, 54, 'link', '', 'cms', '3', '', '', '', '', 0, 1, '_self', 2),
(75, 54, 'link', '', 'cms', '3', '', '', '', '', 0, 1, '_self', 3),
(76, 54, 'link', '', 'link', 'my-account.php', '', '', '', '', 0, 1, '_self', 4),
(77, 55, 'link', '', 'link', 'contact-form.php', '', '', '', '', 0, 1, '_self', 0),
(78, 55, 'link', '', 'link', 'discount.php', '', '', '', '', 0, 1, '_self', 1),
(79, 55, 'link', '', 'cms', '1', '', '', '', '', 0, 1, '_self', 2),
(80, 55, 'link', '', 'link', 'manufacturer.php', '', '', '', '', 0, 1, '_self', 3),
(81, 56, 'link', '', 'link', 'supplier.php', '', '', '', '', 0, 1, '_self', 2),
(82, 56, 'link', '', 'link', 'best-sales.php', '', '', '', '', 0, 1, '_self', 0),
(83, 56, 'link', '', 'link', 'new-products.php', '', '', '', '', 0, 1, '_self', 3),
(84, 56, 'link', '', 'link', 'http://landofcoder.com/demo/prestashop14x/', '', '', '', '', 0, 1, '_self', 1),
(86, 46, 'module', '', '', '', 'lofnewsletter', 'footer', '', '', 0, 0, '', 0),
(87, 57, 'module', '', '', '', 'loftwitter', 'footer', '', '', 0, 0, '', 0),
(88, 46, 'custom_html', '', '', '', '', '', '', '', 0, 1, '', 1),
(89, 58, 'custom_html', '', '', '', '', '', '', '', 0, 0, '', 0);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item_lang` (
  `id_loffc_block_item` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `text` text NOT NULL
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_item_lang` (`id_loffc_block_item`, `id_lang`, `title`, `text`) VALUES
(78, 4, 'Discount', ''),
(78, 5, 'Discount', ''),
(78, 6, 'Discount', ''),
(79, 1, 'Delivery', ''),
(79, 2, 'Delivery', ''),
(79, 3, 'Delivery', ''),
(79, 4, 'Delivery', ''),
(79, 5, 'Delivery', ''),
(79, 6, 'Delivery', ''),
(0, 1, 'item 1', ''),
(0, 2, 'item 1', ''),
(0, 3, 'item 1', ''),
(0, 4, 'item 1', ''),
(0, 5, 'item 1', ''),
(0, 6, 'item 1', ''),
(80, 3, 'Manufactures', ''),
(80, 4, 'Manufactures', ''),
(80, 5, 'Manufactures', ''),
(80, 1, 'Manufactures', ''),
(80, 2, 'Manufactures', ''),
(77, 5, 'Contact', ''),
(77, 6, 'Contact', ''),
(78, 1, 'Discount', ''),
(78, 2, 'Discount', ''),
(78, 3, 'Discount', ''),
(77, 4, 'Contact', ''),
(75, 3, 'Privacy Policy', ''),
(75, 4, 'Privacy Policy', ''),
(75, 5, 'Privacy Policy', ''),
(75, 6, 'Privacy Policy', ''),
(76, 1, 'Your account', ''),
(76, 2, 'Your account', ''),
(76, 3, 'Your account', ''),
(76, 4, 'Your account', ''),
(76, 5, 'Your account', ''),
(76, 6, 'Your account', ''),
(77, 1, 'Contact', ''),
(77, 2, 'Contact', ''),
(77, 3, 'Contact', ''),
(80, 6, 'Manufactures', ''),
(81, 1, 'Supplier', ''),
(81, 2, 'Supplier', ''),
(81, 3, 'Supplier', ''),
(81, 4, 'Supplier', ''),
(81, 5, 'Supplier', ''),
(72, 1, 'Terms', ''),
(72, 2, 'Terms', ''),
(72, 3, 'Terms', ''),
(72, 4, 'Terms', ''),
(72, 5, 'Terms', ''),
(72, 6, 'Terms', ''),
(73, 1, 'About us', ''),
(73, 2, 'About us', ''),
(73, 3, 'About us', ''),
(73, 4, 'About us', ''),
(73, 5, 'About us', ''),
(73, 6, 'About us', ''),
(74, 1, 'Address', ''),
(74, 2, 'Address', ''),
(74, 3, 'Address', ''),
(74, 4, 'Address', ''),
(74, 5, 'Address', ''),
(74, 6, 'Address', ''),
(75, 1, 'Privacy Policy', ''),
(75, 2, 'Privacy Policy', ''),
(82, 2, 'Top seller', ''),
(82, 1, 'Top seller', ''),
(81, 6, 'Supplier', ''),
(84, 6, 'Phone: (84) 123 456 789', ''),
(84, 5, 'Phone: (84) 123 456 789', ''),
(84, 4, 'Phone: (84) 123 456 789', ''),
(84, 3, 'Phone: (84) 123 456 789', ''),
(84, 2, 'Phone: (84) 123 456 789', ''),
(84, 1, 'Tracking Packages', ''),
(83, 6, 'New product', ''),
(83, 5, 'New product', ''),
(83, 4, 'New product', ''),
(83, 3, 'New product', ''),
(83, 2, 'New product', ''),
(83, 1, 'New product', ''),
(82, 6, 'Top seller', ''),
(82, 5, 'Top seller', ''),
(82, 4, 'Top seller', ''),
(82, 3, 'Top seller', ''),
(86, 1, 'Newsletter', ''),
(86, 2, 'Newsletter', ''),
(86, 3, 'Newsletter', ''),
(86, 4, 'Newsletter', ''),
(86, 5, 'Newsletter', ''),
(86, 6, 'Newsletter', ''),
(87, 1, 'twitter', ''),
(87, 2, 'twitter', ''),
(87, 3, 'twitter', ''),
(87, 4, 'twitter', ''),
(87, 5, 'twitter', ''),
(87, 6, 'twitter', ''),
(88, 1, 'Social network', '<ul>\r\n<li class=\"facebook\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"twitter\"><a href=\"#\">rss</a></li>\r\n<li class=\"skype\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"youtube\"><a href=\"#\">Skype</a></li>\r\n</ul>'),
(88, 2, 'Social network', ''),
(88, 3, 'Social network', ''),
(88, 4, 'Social network', ''),
(88, 5, 'Social network', ''),
(88, 6, 'Social network', ''),
(89, 1, 'Copyright', '<div class=\"copyright\">\r\n<small>Copyright &copy; 2012 <a href=\"#\">Leo_Tshirt</a>.All Rights Reserved Designed by <a href=\"http://www.leotheme.com\">Leotheme.com</a>.</small>\r\n</div>
<div class=\"loftop\">\r\n<a href=\"#\">go to top </a>\r\n</div>'),
(89, 2, 'Copyright', ''),
(89, 3, 'Copyright', ''),
(89, 4, 'Copyright', ''),
(89, 5, 'Copyright', ''),
(89, 6, 'Copyright', '');

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_lang` (
  `id_loffc_block` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_lang` (`id_loffc_block`, `id_lang`, `title`) VALUES
(1, 1, 'newletter '),
(1, 2, 'block 1'),
(1, 3, 'block 1 span'),
(1, 4, 'block 1'),
(1, 5, 'block 1'),
(1, 6, 'block 1'),
(55, 6, 'About Dropship'),
(55, 5, 'About Dropship'),
(55, 4, 'About Dropship'),
(54, 4, 'My Account'),
(54, 3, 'My Account'),
(54, 2, 'My Account'),
(54, 1, 'Infomation'),
(55, 3, 'About Dropship'),
(55, 2, 'About Dropship'),
(55, 1, 'Service'),
(54, 6, 'My Account'),
(54, 5, 'My Account'),
(46, 6, 'block 3'),
(46, 5, 'block 3'),
(46, 4, 'block 3'),
(46, 3, 'block 3'),
(46, 1, 'block1'),
(46, 2, 'block 3'),
(56, 4, 'Infomation'),
(56, 5, 'Infomation'),
(56, 6, 'Infomation'),
(56, 3, 'Infomation'),
(56, 1, 'Support'),
(56, 2, 'Infomation'),
(57, 1, 'Recent twitter'),
(57, 2, 'Recent twitter'),
(57, 3, 'Recent twitter'),
(57, 4, 'Recent twitter'),
(57, 5, 'Recent twitter'),
(57, 6, 'Recent twitter'),
(58, 1, 'Copyright'),
(58, 2, 'Copyright'),
(58, 3, 'Copyright'),
(58, 4, 'Copyright'),
(58, 5, 'Copyright'),
(58, 6, 'Copyright');

";
?>
